in_file: "data/GRI_2017_2020 (1) - Copy.xlsx" # Input file
out_file: "data/test.csv"      # Output file
out_pdf_dir: "data/test"       # Directory for the downloaded pdfs
tasks: 20                              # Concurrent downloads
verbose: True                          # Log verbosity 