in_file: "data/Metadata2006_2016.xlsx" # Input file
out_file: "data/metadata2006.csv"      # Output file
out_pdf_dir: "data/metadata2006"       # Directory for the downloaded pdfs
tasks: 20                              # Concurrent downloads
verbose: True                          # Log verbosity 